title = "Kafka Configuration"
[kafka]
TopicName = "KafkaTest001"
BootstrapServers = "192.168.16.12:9094,192.168.16.13:9094"
AutoOffsetReset = "earliest"
EnableAutoCommit = false
ConsumerTimeoutMs = 2000
api_version = "1.1.0"
GroupID = "digitalhermit"
